# Hydrogen

spacing         = 1
padding         = 0
hide_ascii      = true
separator       = ">"
key_color       = "Cyan"
separator_color = "White"

[palette]
type    = "Dark"
glyph   = "ï„‘   "
visible = true

[bar]
glyph           = "ß‹"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = false

[box]
title           = " System Information ğŸ’» "
border          = "plain"
visible         = true

[box.inner_margin]
x               = 1
y               = 1

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "ï€•  host"
kernel          = "ó°Œ½  kernel"
battery         = "ó°¹  battery"
os              = "ï€“  os"
de              = "ï’©  de"
wm              = "ï‹  wm"
distro          = "ï€“  distro"
terminal        = "ï’‰  terminal"
shell           = "ï…•  shell"
packages        = "ï’‡  packages"
uptime          = "ó°¥”  uptime"
memory          = "î¿…  memory"
machine         = "ó°‡…  machine"
local_ip        = "ó°±“  ip"
backlight       = "ó°ƒ  brightness"
resolution      = "ó°º  resolution"
cpu_load        = "ó°Šš  cpu load"
cpu             = "ï’¼  cpu"
gpu             = "ó°ˆ  gpu"
disk_space      = "ïƒ‡  disk space"